In [1]:
import yfinance as yf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data=yf.download('BTC-USD','2018-01-01','2024-01-01')

[*********************100%%**********************]  1 of 1 completed


In [4]:
data.head()

Open          High           Low         Close  \
Date                                                                 
2018-01-01  14112.200195  14112.200195  13154.700195  13657.200195   
2018-01-02  13625.000000  15444.599609  13163.599609  14982.099609   
2018-01-03  14978.200195  15572.799805  14844.500000  15201.000000   
2018-01-04  15270.700195  15739.700195  14522.200195  15599.200195   
2018-01-05  15477.200195  17705.199219  15202.799805  17429.500000   

               Adj Close       Volume  
Date                                   
2018-01-01  13657.200195  10291200000  
2018-01-02  14982.099609  16846600192  
2018-01-03  15201.000000  16871900160  
2018-01-04  15599.200195  21783199744  
2018-01-05  17429.500000  23840899072

In [5]:
data=pd.DataFrame(data)

In [6]:
data.reset_index(inplace=True)

In [7]:
data

Date          Open          High           Low         Close  \
0    2018-01-01  14112.200195  14112.200195  13154.700195  13657.200195   
1    2018-01-02  13625.000000  15444.599609  13163.599609  14982.099609   
2    2018-01-03  14978.200195  15572.799805  14844.500000  15201.000000   
3    2018-01-04  15270.700195  15739.700195  14522.200195  15599.200195   
4    2018-01-05  15477.200195  17705.199219  15202.799805  17429.500000   
...         ...           ...           ...           ...           ...   
2186 2023-12-27  42518.468750  43683.160156  42167.582031  43442.855469   
2187 2023-12-28  43468.199219  43804.781250  42318.550781  42627.855469   
2188 2023-12-29  42614.644531  43124.324219  41424.062500  42099.402344   
2189 2023-12-30  42091.753906  42584.125000  41556.226562  42156.902344   
2190 2023-12-31  42152.097656  42860.937500  41998.253906  42265.187500   

         Adj Close       Volume  
0     13657.200195  10291200000  
1     14982.099609  16846600192  
2     15201.000000  16871900160  
3     15599.200195  21783199744  
4     17429.500000  23840899072  
...            ...          ...  
2186  43442.855469  25260941032  
2187  42627.855469  22992093014  
2188  42099.402344  26000021055  
2189  42156.902344  16013925945  
2190  42265.187500  16397498810  

[2191 rows x 7 columns]

In [8]:
print("rows",data.shape[0],"columns",data.shape[1])

rows 2191 columns 7


In [9]:
#checking the null values
data.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

### Ploting the data

In [28]:
plt.figure(figsize=(10,12))
plt.plot(data)
plt.show()

In [11]:
x=data[['Open','High','Low','Volume']]
y=data['Close']

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.20,random_state=42)

### Linear Regression

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
log=LinearRegression()

In [14]:
log.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred1=log.predict(x_test)

In [16]:
y_pred1.shape

(439,)

In [17]:
dframe=pd.DataFrame(y_test,y_pred1)

In [18]:
df=pd.DataFrame({'Actual Price':y_test,'Predicted Price':y_pred1})
print(df)

      Actual Price  Predicted Price
382    3657.839355      3641.114220
632    8486.993164      8518.971910
1670  23804.632812     23920.724053
211    7780.439941      7831.154004
1488  37784.332031     37114.702187
...            ...              ...
674    9360.879883      9360.503847
1511  38431.378906     38643.178209
1192  56048.937500     56763.658615
1102  39371.042969     39472.324289
1980  27119.066406     27190.435726

[439 rows x 2 columns]


In [19]:
log.score(x_test,y_test)

0.9995150978656064

In [20]:
acc_score = r2_score(y_pred1, y_test)
print(acc_score)


0.9995145863824539


### Using Label Encoding to covert continious data

In [21]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix

In [22]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
y_test_encoded = lab.fit_transform(y_test)



### Random Forest Classifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_test,y_test_encoded)


RandomForestClassifier()

In [24]:
r_pred1=rf.predict(x_test)


In [25]:
accuracy_score(y_test_encoded,r_pred1)


1.0

In [26]:
y_pred_test=rf.predict(x_test)
conf_metrix = confusion_matrix(y_pred_test, y_test_encoded)
print(conf_metrix)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
